main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('projects', views.projects, name='projects')
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='story1')
]

story3django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1', include('story1.urls')),
    path('story5', include('story5.urls')),
    path('story6', include('story6.urls')),
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.story5, name='story5'),
    path('creatematkul', views.creatematkul, name='creatematkul'),
    path('<slug:slug>/', views.matkul_detail, name='matkul_detail'),
    path('delete/<int:id>', views.delete, name='delete'),
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.story6, name='story6'),
]

main/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.
class MataKuliah(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()
    dosen = models.TextField()
    sks = models.PositiveSmallIntegerField()
    semester = models.CharField(max_length=50)
    ruang = models.CharField(max_length=50)
    desc = models.TextField()
    
    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.name)

        super(MataKuliah, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name

#    class Meta:
#        verbose_name = _("MataKuliah")
#        verbose_name_plural = _("MataKuliahs")



#    def get_absolute_url(self):
#        return reverse("MataKuliah_detail", kwargs={"pk": self.pk})

story6/models.py
from django.db import models

class Kegiatan(models.Model):
    namaKegiatan = models.CharField(max_length=30)

    def __str__(self):
        return self.namaKegiatan

class Peserta(models.Model):
    namaPeserta = models.CharField(max_length=30)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE, related_name='peserta')

    def __str__(self):
        return self.namaPeserta

story5/forms.py
from django import forms
from . import models

class CreateMatkul(forms.ModelForm):
    class Meta:
        model = models.MataKuliah
        fields = ['name', 'dosen', 'sks', 'semester', 'ruang', 'desc']

story6/forms.py
from django import forms
from . import models

class CreateKegiatan(forms.ModelForm):
    class Meta:
        model = models.Kegiatan
        fields = ['namaKegiatan']

class TambahPeserta(forms.ModelForm):
    class Meta:
        model = models.Peserta
        fields = ['namaPeserta', 'kegiatan']

main/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main/index.html')

def projects(request):
    return render(request, 'main/portofolio.html')

story1/views.py
from django.shortcuts import render

# Create your views here.
def story1(request):
    return render(request, 'story1/index.html')

story5/views.py
from django.shortcuts import render, redirect
from .models import MataKuliah
from . import forms

# Create your views here.
def story5(request):
    matkuls = MataKuliah.objects.all()
    return render(request, 'story5/index.html', {'matkuls':matkuls})

def creatematkul(request):
    if request.method == "POST":
        form = forms.CreateMatkul(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story5:story5')
    else:
        form = forms.CreateMatkul()
    return render(request, 'story5/create_matkul.html', {'form':form})

def matkul_detail(request, slug):
    matkul = MataKuliah.objects.get(slug=slug)
    return render(request, 'story5/matkul_detail.html', { 'matkul':matkul})

def delete(request,id):
    matkul = MataKuliah.objects.get(id=id)
    matkul.delete()
    return redirect('story5:story5')

story6/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan, Peserta
from . import forms

# Create your views here.
def story6(request):
    pesertas = Peserta.objects.all()
    return render(request, 'story6/isi.html', {'pesertas':pesertas})

def createKegiatan(request):
    if request.method == "POST":
        form = forms.CreateKegiatan(request.POST)
        if form.is_valid():
            return redirect('story6:story6')
    else:
        form = forms.CreateKegiatan()
    return render(request, 'story6/tambahKegiatan.html', {'form':form})

def tambahPeserta(request):
    if request.method == "POST":
        form = forms.CreateKegiatan(request.POST)
        if form.is_valid():
            return redirect('story6:story6')
    else:
        form = forms.CreateKegiatan()
    return render(request, 'story6/tambahPeserta.html', {'form':form})
    

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Welcome.</title>
{% endblock meta %}

{% block content %}
    <section id="home">
        <div class="container mt-5">
            <div class="card showcard shadow">
                <div class="row">

                    <div class="col-md-4">
                        <img src="{% static 'img/pp.png' %}" class="img-fluid">
                    </div>

                    <div class="col-md-8 mt-3">
                        <h2 id="greeting">What's up</h2>
                        <p id="perkenalan">I am currently a computer science
                            student at the University of Indonesia
                            looking to get a job as a front end
                            developer at your company. In this
                            site, you will have access to my contact
                            information, my social media, and my
                            previous works I have done for my
                            campus and other organizations.

                            Got a question? Email me!
                        </p>
                        <a href = "mailto: arllivandhya.dani@ui.ac.id">
                        <img src="{% static 'img/Component 5.png' %}" class="img-fluid my-icons"></a>
                    </div>

                </div>
                <div class="row justify-content-md-center soc-med my-icons">
                    <div class="row justify-content-center">

                        <div class="col justify-content-center">
                            <a href="https://www.facebook.com/arvand01/">
                            <img src="{% static 'img/Facebook.png' %}" class="img-fluid img-respond"></a>
                        </div>

                        <div class="col justify-content-center">
                            <a href="https://www.instagram.com/ar.lli/">
                            <img src="{% static 'img/Instagram.png' %}" class="img-fluid img-respond"></a>
                        </div>

                        <div class="col justify-content-center">
                            <a href="https://twitter.com/benjibeki">
                            <img src="{% static 'img/Twitter.png' %}" class="img-fluid img-respond"></a>
                        </div>

                        <div class="col justify-content-center">
                            <a href="https://gitlab.com/vandhya">
                            <img src="{% static 'img/Git.png' %}" class="img-fluid img-respond"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="edu">
        <div class="row">
            <div class="col-md-8">
                <div class="container riwayat">
                    <div class="row">
                        <h1>Universitas Indonesia</h1>
                    </div>
                    <div class="row">
                        <p>Fakultas Ilmu Komputer (2019-2023)</p>
                    </div>
                    <div class="row">
                        <h1>SMA Negeri 1 Bogor</h1>
                    </div>
                    <div class="row">
                        <p>2016-2019</p>
                    </div>
                    <div class="row">
                        <h1>SMP Budi Mulia Bogor</h1>
                    </div>
                    <div class="row">
                        <p>2013-2016</p>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <img src="{% static 'img/edu.png' %}" class="img-fluid">
            </div>
        </div>
    </section>

    <section id="port">
        <a href="{% url 'main:projects' %}">
        <img src="{% static 'img/port.png' %}" class="img-fluid"></a>
        <a href="#home">
        <img src="{% static 'img/Vector 2.png' %}" class="img-fluid" style="margin: 100px; margin-bottom: 0px;"></a>
    </section>
{% endblock content %}

main/templates/main/portofolio.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Previous Projects</title>
{% endblock meta %}

{% block content %}
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'img/a (1).png' %}" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <h5>Vector Arts</h5>
                <p>Vector arts using Adobe Illustrator made for my own enjoyment</p>
              </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/pemira1.png' %}" alt="Second slide">
            <div class="carousel-caption d-none d-md-block">
                <h5>Pemira 2019</h5>
                <p>One of my works from being part of media, creative, and documentation in Fasilkom's Pemira</p>
              </div>
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/finalists_blured.png' %}" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
                <h5>Smansa Punya Liga</h5>
                <p>An example of my work from high school, in an soccer event called SPL</p>
              </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
{% endblock content %}

story1/templates/story1/index.html
{% load static %}
<html>

<head>
    <title>Story 1- Arllivandhya Dani</title>
</head>

<body>
    <h1>Profile</h1>
    <img src="{% static 'img/the_only_good_photo_of_me.jpg' %}" alt="big think" width="240 px">
    <p>Nama: Arllivandhya Dani <br>
        NPM: 1906398521<br>
        Angkatan: Maung 2019<br>
        Tempat kuliah: Fasilkom UI<br>
        Hobi: Game nfs di ps2<br>
    </p>
    <p>Mahasiswa semester 3 di Fakultas Ilmu Komputer Universitas Indonesia yang terobsesi dengan segala sesuatu
        mengenai otomotif</p>
    <table style="table-layout: fixed; width: 368px">
        <tr>
            <td>SMP</td>
            <td>SMP Budi Mulia Bogor</td>
        </tr>
        <tr>
            <td>SMA</td>
            <td>SMA Negeri 1 Bogor</td>
        </tr>
        <tr>
            <td>Pendidikan tinggi</td>
            <td>Universitas Indonesia</td>
        </tr>
    </table>
    <a href="https://www.twitter.com/benjibeki">
        <img src="{% static 'imgtwt.png' %}" alt="twitter icon" width="36 px">
    </a>
</body>

</html>

story5/templates/story5/create_matkul.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Add Schedule</title>
{% endblock meta %}

{% block content %}
<div class="create-matkul">
    <h2>Add schedule</h2>
    <form class="site-form" action="{% url 'story5:creatematkul' %}" method="POST">
        {% csrf_token %}
        {{form}}
        <input class="btn btn-success" type="submit" value="Add">
    </form>
</div>
{% endblock content %}

story5/templates/story5/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Schedule</title>
{% endblock meta %}

{% block content %}
<div>
</div>

<div class="matkul-list">
    <div class="container">
        <div class="intro">
            <h2 class="text-center">Course Schedule</h2>
            <a href="{% url 'story5:creatematkul' %}"><button type="button" class="btn btn-outline-warning btn-lg btn-block add-btn">Add schedule</button></a>

        </div>
        <div class="row articles">
            {% for matkul in matkuls %}
            <div class="col-sm-6 item">
                <a href="{% url 'story5:matkul_detail' matkul.slug %}"><h3 class="name">{{ matkul.name }}</h3></a>
                <p class="description">{{ matkul.dosen }}</p>
                <a class="action" href="{% url 'story5:matkul_detail' matkul.slug %}">
                    <i class="fa fa-arrow-circle-right"></i></a>
            </div>
            {% endfor %}

            </div>
        </div>
    </div>
</div>
{% endblock content %}

story5/templates/story5/matkul_detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Course Schedule</title>
{% endblock meta %}

{% block content %}
<div class="container">
<div class="card detail">
  <div class="card-body">
    <h5 class="card-title">{{matkul.name}}</h5>
    <p class="card-text">{{matkul.desc}}</p>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">{{matkul.dosen}}</li>
      <li class="list-group-item">{{matkul.sks}} sks</li>
      <li class="list-group-item">{{matkul.semester}}</li>
      <li class="list-group-item">{{matkul.ruang}}</li>
    </ul>
    <a href="{% url 'story5:delete' matkul.id %}" class="btn btn-danger">Delete</a>
  </div>
</div>
</div>
{% endblock content %}

story6/templates/story6/isi.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Ikut Kegiatan</title>
{% endblock meta %}

{% block content %}
<h1>ASUUUUUUU</h1>
<div class="kegiatan-list">
    <div class="container">
        <div class="intro">
            <h2 class="text-center">Ayo ikut kegiatan</h2>
            <button type="button" class="btn btn-primary btn-lg btn-block">Ikut kegiatan</button>

        </div>


        <div class="row articles">
            {% for peserta in pesertas %}
            
            <div class="col-sm-6 item">
                <h3 class="name">{{ peserta.kegiatan }}</h3>
                <p class="description">{{ peserta.namaPeserta }}</p>
                
            </div>
            {% endfor %}

            </div>
            <button type="button" class="btn btn-primary btn-lg btn-block">Tambah kegiatan</button>
        </div>

</div>


{% endblock content %}

story6/templates/story6/tambahKegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Ayo tambah kegiatan</title>
{% endblock meta %}

{% block content %}
<div class="create-matkul">
    <h2>Add schedule</h2>
    <form class="site-form" action="{% url 'story6:createKegiatan' %}" method="POST">
        {% csrf_token %}
        {{form}}
        <input class="btn btn-success" type="submit" value="Add">
    </form>
</div>
{% endblock content %}

story6/templates/story6/tambahPeserta.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Ayo Ikut Kegiatan</title>
{% endblock meta %}

{% block content %}
<div class="create-matkul">
    <h2>Add schedule</h2>
    <form class="site-form" action="{% url 'story6:tambahPeserta' %}" method="POST">
        {% csrf_token %}
        {{form}}
        <input class="btn btn-success" type="submit" value="Add">
    </form>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css\all.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css\style.css' %}">

    {% block meta %}
    {% endblock meta %}
</head>

<body>
    <!--  Navbar  -->
    <section class="section-1 container-fluid">
        <div class="d-flex flex-column">
            <header>
                <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light shadow">
                    <a class="navbar-brand text-nav" href="{% url 'main:index' %}#home">arllivandhya dani</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                            <a class="nav-link text-nav" href="{% url 'main:index' %}#edu">education</a>
                            <a class="nav-link text-nav" href="{% url 'main:index' %}#port">portfolio</a>
                            <a class="nav-link text-nav" href="{% url 'story5:story5' %}">schedule</a>
                        </div>
                    </div>
                </nav>
            </header>
        </div>
    </section>
    <!-- Navbar end-->

    {% block content %}
    {% endblock content %}
        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>

</body>
</html>